/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
#define YALS_OS "Linux pku 4.15.0-43-generic x86_64"
#define YALS_COMPILED "2020年 01月 19日 星期日 22:10:06 CST"
#define YALS_RELEASED "Do 12. Apr 18:16:13 CEST 2018"
#define YALS_VERSION "sc18"
#define YALS_ID "aa706dabf358f9024b45f8153a7e727322bc8f96"
