#!/bin/sh

die () {
   echo "*** mkconfig: $*" 1>&2
   exit 1
}

[ -f makefile ] || die "can not find 'makefile'"

cat<<EOF
/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
EOF

echo "#define YALS_OS \"`uname -srmn`\""
echo "#define YALS_COMPILED \"`date`\""
echo "#define YALS_RELEASED \"Do 12. Apr 18:16:13 CEST 2018\""
echo "#define YALS_VERSION \"sc18\""
echo "#define YALS_ID \"aa706dabf358f9024b45f8153a7e727322bc8f96\""
