# Makefile for coprocessor preprocessor
# Copyright (c) 2012-2013, Norbert Manthey

EXEC      = coprocessor
DEPDIR    = mtl utils core

CFLAGS    += $(INCFLAGS)
LFLAGS    += $(INLDFLAGS)

include $(MROOT)/mtl/template.mk
